environment_config:
  path: common/environment_config.dart
  dotenv_path: .env
  class: EnvironmentConfig

  fields:
    SAFEZONE_API_URL:
      dotenv: true
      default: <REQUIRED>
    SAFEZONE_WEBSOCKET_URL:
      dotenv: true
      default: <REQUIRED>
    ENV:
      dotenv: true
      default: dev
    SENTRY_DSN:
      dotenv: true
      default: <REQUIRED>
